### ISSUE TITLE
Not receiving response after writing to the Serial Port 

### ISSUE THREAD

**Issue by shubham9436** [xseignard/cordovarduino#116]
I am trying to build an application using Ionic Framework. I have seen the example as given on their site [https://ionicframework.com/docs/native/serial](url) . 

The same way even I have declared a constructor in which I have registered a callback function to read the response from the serial port. Then I have click button to send the data.

The problem is that when the application starts, it is receiving the messages perfectly but when I write to the serial port, the application stops receving. I have tried to put various debug points, but I am still not able to figure out the problem.

**Comment by kappapl** [comment]
Hi Shubham, have you fixed this problem? 
I have the same.

**Comment by shubham9436** [comment]
Yes, I have fixed the problem. Mostly the reason would be that the sender's device needs to send data in some particular format which is understandable by the receiver's device.
