### ISSUE TITLE
question/install

### ISSUE THREAD

**Issue by ndvalkov** [xseignard/cordovarduino#12]
Hello,

Sorry to bother you again, but how can I get access to the 'serial' object after installing the plugin as instructed in the readme file?

I am not sure if I need to have the usbserialforandroid library already installed, with the respective configurations you have to adjust. I tried to include the serial.js in the head, other things..

I see there is ng-cordova that provides easy to use JavaScript API, but I think it works only with the standard Cordova plugins.

Seems like trivial stuff, but has taken me a while now to figure it out. Very annoying.

**Comment by surajjorwekar** [comment]
Hello @ndvalkov can you share your project ?

**Comment by ChoseKurosa** [comment]
@ndvalkov Can u please show me how u did this: "I did smthg like document.write(serial.read) in that scope and missed it:), but with an alert(), on the device, it was visible. Then injected $rootScope and attached the object to it so it can be used from the controllers." exactly. I really don't know what does it mean. Just part in module. How to inject rootScope with serial object.
