### ISSUE TITLE
FT312D Support

### ISSUE THREAD

**Issue by crapthings** [xseignard/cordovarduino#17]
http://www.ftdichip.com/Products/ICs/FT312D.html

**Comment by xseignard** [comment]
Any updates @crapthings ?

**Comment by crapthings** [comment]
312d is mini usb that can plug to android device directly without a convertor. but there's no one work as a cordova plugin.

@xseignard  ~~  Is it possible of accept permission automated ?

**Comment by xseignard** [comment]
Hello @crapthings, please check #31
