### ISSUE TITLE
How to use serial.read()?

### ISSUE THREAD

**Issue by crapthings** [xseignard/cordovarduino#18]
Is this for read last sent bytes or it is using by inside the registerReadCallback ?

I use an android phone and connect to a pc node-serial that whatever android send some data, it just sends back.

I've put serial.read inside write success callback and register read callback, but it can't get any data.

How to use that ?

**Comment by xseignard** [comment]
Any updates @crapthings ?

**Comment by crapthings** [comment]
hey @xseignard registerReadCallback works great. but still don't know how and when to use read function.

**Comment by xseignard** [comment]
The truth is that I may remove `serial.read()` as it is a bit useless, because it mean that you would need to know exactly when you need to read, and that's almost impossible to know it, and to time it.

**Comment by xseignard** [comment]
I'll update the code sample in the README, according to this.

**Comment by xseignard** [comment]
Should be ok to close it then,

Feel free to reopen it if needed.

Regards
