### ISSUE TITLE
Cordovarduino Plugin Alert (Error: No Device Found)

### ISSUE THREAD

**Issue by sakibnaz** [xseignard/cordovarduino#23]
Hi All.

For my project I need to interface external Serial Device with Android.  My Device is not a regular Android Phone/Tablet. I am using "BeagleBone Black (http://beagleboard.org/BLACK)" Device with Android 4.4 and LCD Touch Display.

I have made a Visual Studio 2015 Cordova project and added Cordovarduino Plugin then added the example code in Index.JS file under onDeviceReady(). Below is the code:

    function onDeviceReady() {
        // Handle the Cordova pause and resume events
        document.addEventListener( 'pause', onPause.bind( this ), false );
        document.addEventListener( 'resume', onResume.bind( this ), false );
       
        // TODO: Cordova has been loaded. Perform any initialization that requires Cordova here.

		// Cordovarduino Start
        var errorCallback = function (message) {
            alert('Error: ' + message);
        };

        serial.requestPermission(
            {vid: '0403', pid: '6001'},
            function (successMessage) {
                serial.open(
                    { baudRate: 9600 },
                    function (successMessage) {
                        serial.write(
                            '1',
                            function (successMessage) {
                                alert(successMessage);
                            },
                            errorCallback
                        );
                    },
                    errorCallback
                );
            },
            errorCallback
        );
		// Cordovarduino End	
    };

Unfortunately when I am running the Apps, it's giving me an Alert: "Error: No Device Found". I have added the VID and PID in the code which I get from 'dmesg" command. I am using a FTDI Serial cable for testing.

Can you please advise to overcome the problem?

Apologies, if my ques is silly. I am new learner in Android Development.

Thanks in advance.

Regards.

**Comment by xseignard** [comment]
Hello,

I don't have a BBB to test, but can you try to give the result of a `lsusb` command with AND without your FTDI cable?

Then we'll be able to check what's wrong.

Regards,

Xavier

**Comment by sakibnaz** [comment]
Hi Xavier.

Thanks for reply. Attached is the lsusb output.

![ftdi_lsusb](https://cloud.githubusercontent.com/assets/6670151/5946301/deba2014-a75e-11e4-8696-be71e565bd60.PNG)

Any advise?

Regards.

**Comment by xseignard** [comment]
Hello @sakibnaz did you make progress? unfortunately, I can't see anything wrong, and can't test since i have no BBB

**Comment by xseignard** [comment]
Hello @sakibnaz 
I feel sorry I cannot help you more, did you made any progress?

**Comment by sakibnaz** [comment]
Hi Xavier.

Thanks for looking into the issue. No, I did not able to solve the issue with Cordova. But I found another Serial App (Java ADT based) with Drivers ... which worked with me. So I switched my project to Java ADT.

But I have a plan again to test the Cordovarduino. I'll update here if any progress.

Thanks.
