### ISSUE TITLE
Double/ Triple commands

### ISSUE THREAD

**Issue by Davidx7** [xseignard/cordovarduino#24]
Maybe I'm doing something wrong, but I need to send via serial 2 commands, with hex codes and then the device goes into data broadcast mode

Each time I do 2 x serial.write or 2 x serial.writeHex, the app crashes instantly. 

Also, when I do only 1 and then serial.read of it, nothing comes, doesn't even trigger the alert inside of it. 

Is this a common problem?

**Comment by xseignard** [comment]
Please give more details, such as code and what are the devices you use (android AND the serial one).

**Comment by Davidx7** [comment]
So, what I want to send to the device is the ESC key that will open it's menu and then the 3 key which will get it to output readings every 2 seconds

Every 2 seconds the device will output a new line looking like this :: "2000/01/07 12:23:43, 1.34, 38124"
Obviously the timestamp is wrong, but the 2nd and 3rd part of the string is what I need. 

Android         = Note 4
Serial Device = data logger from combine tractor. (works very well, I tested it in terminal app on my phone, no problems), I just need it to work in my app 

Problem:: 
Whatever I try, in whatever way I try to send a 2nd writeHex() or write() command, the app will crash, with or without a timeout. 

```javascript
window.serial.requestPermission(
                function(successMessage) {
                    window.serial.open({baudRate: 9600},
                        function(successMessage) {
                            window.serial.writeHex('1B',function(successMessage) { // 1B = ESC key
                                  
                                  $timeout(function() { // timeout object from angular. can be any timeout
                                     window.serial.writeHex('3',function(successMessage) {// 3 = 3 option number 3
                                            window.serial.registerReadCallback(
                                              function(data){
                                                  var view = new Uint8Array(data);

                                                  $scope.endResult += $scope.uintToString(data);
                                              },
                                              function(){
                                                  alert("Failed to register read callback");
                                              });
                                      },function(message) { alert('Error failed to send key :: 3: ' + message);});
                                  }, 500);

                              },function(message) { alert('Error failed to send key :: ESC: ' + message);});
                        },function(message) { alert('Error: serial.open' + message);}
                    );
                },function(message) { alert('Error requestPermission: ' + message);}
            );
```

**Comment by Davidx7** [comment]
UPDATE :+1: 

I used the a terminal app from the playstore to send the commands ESC and then 3 to get it in realtime mode to output readings and then switched back to my app and used this and it works great!:: 

The only problem still is sending 2 key commands. When I send first one, I get the last line of the menu -- there are about 10 lines of text, only get the last one (so it works), but sending the second command will crash the app 

````javascript
window.serial.requestPermission(
                function(successMessage) {
                    window.serial.open({baudRate: 9600},
                        function(successMessage) {
                          window.serial.registerReadCallback(
                            function(data){
                                var view = new Uint8Array(data);
                                $scope.endResult += $scope.uintToString(data);

                            },
                            function(){
                                alert("Failed to register read callback");
                            });
                        },
                        function(message) { alert('Error: serial.open' + message);}
                    );
                },
                function(message) { alert('Error requestPermission: ' + message);}
            );
````

**Comment by xseignard** [comment]
Hello,

Could you run `adb` via wifi and check for some logs, first connect your anrdoid device to your computer and then run the following:
```
adb tcpip 5555
adb connect 192.168.1.10
```

Where 192.168.1.10 is the IP address of your tablet.

Now you can unplug your tablet and `adb` will debug your app over wifi.

Now you can have a look in the logcat to search for some errors.Your can run the following to check for some `console.log` messages.

```
adb logcat | grep CordovaLog
```

Hope this helps, but I'm sure we'll find a solution.

Regards

**Comment by xseignard** [comment]
Hello @Davidx7 any updates?

**Comment by xseignard** [comment]
Without updates i close the issue
