### ISSUE TITLE
Serial Not Found

### ISSUE THREAD

**Issue by darwinnacionales** [xseignard/cordovarduino#26]
Hi, 
I'm trying to use this and followed the steps mentioned. However, I'm getting serial not found error. Have I missed doing something?

**Comment by xseignard** [comment]
Hello,

Please provide more detailled info. Like version of android, type of hardware, pid & vid of your serial device, and so on.

Regards,

Xavier

**Comment by darwinnacionales** [comment]
Hi, Sorry about the lack of details.
I have installed the plugin as instructed:

cordova plugin add https://github.com/xseignard/cordovarduino.git

Then, used the codes shown here: https://github.com/xseignard/cordovarduino

![image](https://cloud.githubusercontent.com/assets/7297625/6323505/85e44458-bb66-11e4-8a77-102c9d43f4a3.png)

However, I get the error: "ReferenceError: serial is not defined". It seems that it cannot find the serial.js but I am not sure if I am adding it the wrong way.

Do I also have to modify anything in config.xml and AndroidManifest.xml?

I am using Samsung Galaxy S3 and Acer A500.
Galaxy S3 : Android version 4.1.1
Acer A500 : Android 4.0.3

I would get back to you on the PID and VID. But have I missed out anything based from the above?

Source codes:

HTML:

<script src="../plugins/serialtest/www/serial.js"></script>
		<script type="text/javascript" charset="utf-8">
			function sendSerial() {
				try {
					serial.requestPermission(function(successMessage) {
						serial.open({
							baudRate : 9600
						}, function(successMessage) {
							serial.write('1', function(successMessage) {
								alert(successMessage);
							}, errorCallback);
						}, errorCallback);
					}, errorCallback);

				} catch(err) {
					alert(err);
				}
			};

			var errorCallback = function(message) {
				alert('Error: ' + message);
			};
		</script>
		<title>Hello World</title>
	</head>
	<body>
		<input type="button" value="Submit" onclick="sendSerial()" />
	</body>

config.xml

<?xml version='1.0' encoding='utf-8'?>
<widget id="com.testtest.testtesttest" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>TestTestTest</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <access origin="*" />
</widget>

AndroidManifest.xml:

<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="1" android:versionName="0.0.1" package="com.jaranacio.uberlike" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@drawable/icon" android:label="@string/app_name">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="CordovaApp" android:theme="@android:style/Theme.Black.NoTitleBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
    <uses-sdk android:minSdkVersion="10" android:targetSdkVersion="19" />
</manifest>

**Comment by xseignard** [comment]
Do you run a `cordova build`?

**Comment by darwinnacionales** [comment]
I actually did not as I was still testing it using PhoneGap Desktop App. Would try that and get back to you on this. Thank you!

**Comment by xseignard** [comment]
Hello @darwinnacionales any updates?

**Comment by darwinnacionales** [comment]
Hello, I was able to make it work.
I opened the apk file generated after build and realized that it has a different folder structure so I copied the serial.js file to my js directory.

Thanks for this!
