### ISSUE TITLE
ReadCallBack Data Loss

### ISSUE THREAD

**Issue by darwinnacionales** [xseignard/cordovarduino#27]
Hello, Good day!

I have encountered an issue when reading data from arduino. As I understand it, registerReadCallback should automatically be called once it receives data from the serial.

Based on my testing, only one char is passed at a time. Is this to be expected?

I tried to adjust my codes in that way were in only one char is received at a time. However, there are some characters that are missing. For example, I'm sending the text "Data Received" from Arduino to Phonegap. I might be receiving:
Data Received
DtaRecvd
Data Rvd
or any other variations.

Would you know what might have caused this? I used the same codes in the example provided. And it seems that arduino is able to send the right data based on testing it with passing data from arduino to pc.

Thanks!

**Comment by xseignard** [comment]
It should work OK, please ALWAYS provide details and some code that reproduces the bug you're experiencing.

Also take a look at that code sample https://gist.github.com/tobeee/384b63689501367517fe

**Comment by xseignard** [comment]
No updates, I close the issue, please reopen it if needed.
