### ISSUE TITLE
what is wrong with my implementation ? 

### ISSUE THREAD

**Issue by amine-benselim** [xseignard/cordovarduino#28]
hello 
i am trying to connect my android device to an arduino uno , and i found your plugin to be very helpful 
here is the code i used in my arduino
its a simple program that presumably blinks the built in led of the board when it receives serial data
 ```

void setup() {
  // initialize serial communications at 9600 bps:
  Serial.begin(9600); 
  pinMode(13, OUTPUT);     
}

void loop() {
    if (Serial.available() > 0) {
                // read the incoming byte:
              digitalWrite(13, HIGH);   // turn the LED on (HIGH is the voltage level)
              delay(1000);               // wait for a second
              digitalWrite(13, LOW);    // turn the LED off by making the voltage LOW
              delay(1000);        
        }
}
```
and for the android side , i initiated a new phonegap project , added your plugin , and edited the following part of the index.js file 
```
onDeviceReady: function() {
        serial.requestPermission(function success(), function error());
	serial.open({baudRate:9600}, function success(), function error());
	  while(1) {
	   serial.write('1', function success(), function error());
	  }	
    },
```

but i got no response in my arduino board, could you please tell me what am i doing wrong ?

**Comment by xseignard** [comment]
try that on the android side

```javascript
onDeviceReady: function() {
  var errorCallback = function(message) {
    alert('Error: ' + message);
  };
  serial.requestPermission(
    function(successMessage) {
      serial.open(
        {baudRate: 9600},
        function(successMessage) {
          serial.write('1', function(successMessage) {}, errorCallback);
        },
        errorCallback
      );
    },
    errorCallback
  );
},
```

you need to handle the opening of the serial port on the sucess callback of the request permission.

**Comment by abens241** [comment]
okey, i have tried your response, but when running the app i get an error ( no device found ) , could it be that my arduino uno is not supported ? its not an original one , do u think i shld try requesting the permission using the PID/VID ?

**Comment by abens241** [comment]
update: i tried requesting using the pid/vid method but it didnt work  , please is there an alternative ? this is a crucial step for my project :'(

**Comment by xseignard** [comment]
what is your android version? arduino uno should definitely work.

**Comment by abens241** [comment]
my android version is 4.0.4 (phone samsung GT-S5301 )

**Comment by xseignard** [comment]
what is the pid/vid of your arduino?

with the info you provided, it seems it should work.

**Comment by abens241** [comment]
here are the PID/VID :
USB\VID_2341&PID_0043&REV_0001
USB\VID_2341&PID_0043

i added the request this way 

```
serial.requestPermission({vid: '2341', pid: '0043'},
    function(successMessage) { // requesting the permission was ok
      serial.open(
        {baudRate: 9600}, // options
        function(successMessage) { // opening is successful
          serial.write('1', function(successMessage) {}, errorCallback);
        },
```

**Comment by xseignard** [comment]
please try without the commas

**Comment by xseignard** [comment]
also could you try the following:

`{ vid: '0x2341', pid:' 0x0001' }` this time with the commas

**Comment by xseignard** [comment]
Any updates?

**Comment by xseignard** [comment]
No updates, I close the issue, reopen it if you need to.
