### ISSUE TITLE
Is this working for the browser/Ubuntu target?

### ISSUE THREAD

**Issue by lovebes** [xseignard/cordovarduino#30]
Xavier, I've emailed you and left a message on the Google group for usb-serial-android, and I'd like to apologize for my frantic attempts to reach you.

I'm trying to use the browser version of your plugin, but can't get through the permission acquiring stage. It seems Cordova can't seem to find it inside the commandproxy array, and the error message I keep getting is "Missing Command Error".

I don't know if this is because there is no backend behind the serial.js - does it use the ubuntu src or the android src? I am trying to get it working both on the laptop (Ubuntu/LinuxMint) as well as the android device (Nexus 7). Main reason is that I don't know how to make console.log appear on Android (CM12/Lollipop) and I'm afraid if I go down the rabbit hole, it would make the dev turnaround longer than it should.

I'm at my wit's end - I am a newbie and can't seem to find out why it won't work.
The serial USB works, it's tested with arduino IDE. On Linux, so it is a /dev/ttyUSB0 port. I'm so near getting my instrumental opamp output to show up in my android device.. the visualization on HTML5 Canvas is set, all I need is to feed the signal in..

Thanks!
Seungjin Kim

**Comment by xseignard** [comment]
If you want to use this plugin with your browser, you would need a browser side implementation as is there for ubuntu or android.
