### ISSUE TITLE
Connect to specific port /dev/ttyS2

### ISSUE THREAD

**Issue by fabiomig** [xseignard/cordovarduino#32]
Hello everyone!

I want to connect to this specific port. I know that my device is on that port.

How can i do it with this plugin

Cheers

**Comment by xseignard** [comment]
Hello,

Could you use vid/pid instead?

See https://github.com/xseignard/cordovarduino#your-device-is-not-yet-known

Let me know if this helps

**Comment by fabiomig** [comment]
No it not works.

**Comment by fabiomig** [comment]
what i really want is to specify the por to be connect... 

could you hack your plugin to do that?

**Comment by fabiomig** [comment]
*port

**Comment by xseignard** [comment]
What are your devices? (phone and serial device)

What's the purpose of specifiying the port?

**Comment by fabiomig** [comment]
I'm trying to use my printer with cordova.

Right now i've been able to print with Serial Port API sample apk

now, i'm trying to use your plugin to accomplish the same thing.

check the photos.

![dsc_0131](https://cloud.githubusercontent.com/assets/8770466/8527104/b23298ac-2402-11e5-9990-427ce38251dc.JPG)
![dsc_0130](https://cloud.githubusercontent.com/assets/8770466/8527105/b2347ca8-2402-11e5-82a1-03a84f94a943.JPG)

**Comment by xseignard** [comment]
Hello,

What's the result of some `lsusb` with and without the printer plugged?
Could you copy/paste it here. (you can do it with your computer and/or android device)

**Comment by fabiomig** [comment]
lsusb is not showing me this device.

**Comment by xseignard** [comment]
That's weird, it should show up, no?

**Comment by fabiomig** [comment]
well in that serial-usb api apk its /dev/ttyS2

**Comment by xseignard** [comment]
Hello @fabiomig 
I cannot test it since I don't have any device matching your specs to investigate. Do you had any success?

Regards

**Comment by fabiomig** [comment]
Yes. You could check on my repos.

**Comment by xseignard** [comment]
Where exactly?

**Comment by fabiomig** [comment]
https://github.com/fabiomig/serialport-plugin

**Comment by xseignard** [comment]
Thanks,

Do you see any way to merge such fonctionnality to cordovarduino?
