### ISSUE TITLE
phonegap is not calling serial.requestpermission

### ISSUE THREAD

**Issue by harshali893** [xseignard/cordovarduino#33]
Hey, I am new to phonegap rather I should say new to html and javascript as well. I am having some work in company. I want to develop android app using phonegap which communicates with usb serial port.
But serial.requestpermission() is not getting called. I am not getting any error.

I am just showing relevant code
js/index.js
    function onDeviceReady() {
        window.alert("Device is ready!!!");
        serial.requestPermission({vid: 4292, pid: 60000 },
                                  function success() {
                                    window.alert("Success msg!!!");
                                  },
                                  function error() {
                                    window.alert("error msg");
                                  });
    }

I am doing something wrong. Please help me out.
Thanks in advance.

**Comment by xseignard** [comment]
Hello @harshali893 
Sorry for the late reply, but did you managed to solve your problem?

Regards,

Xavier

**Comment by harshali893** [comment]
Hi,
yeah I have just copied the contents of serial.js into my index.js and now it is calling serial.requestPermission .
But now it is executing errorcallback and is giving error class not found
i am not getting what is the issue exeactly.

**Comment by xseignard** [comment]
Please have a look to the  readme in order to see how to use this plugin.

You're doing it wrong.

Regards

**Comment by harshali893** [comment]
I have gone through readme again and I am back to my previous error.
Should I specify path for serial.js in my index.html. Or add something in config.xml of my project.

**Comment by harshali893** [comment]
Now I have removed code of serial.js from index.js

**Comment by harshali893** [comment]
Now I have copied serial.js into my www/js directory.
And serial.requestPermission() is getting called and is returning callback error as class not found.
Please explain what I am doing wrong. Since 8 days I am stuck on it. 
Otherwise I will be fired now. :'(

**Comment by harshali893** [comment]
Hey I have seen one of issues on this site.
So here are the details 
Phonegap version is 5.1.1-0.29.0
Android Device version is 4.3
I am not doing it on emulator.
I am just doing phonegap serve

**Comment by xseignard** [comment]
Please learn to use cordova and post some code.

**Comment by harshali893** [comment]
Okay. I will study it deeply then let's see what I am doing wrong.
Thanks for reply.

**Comment by xseignard** [comment]
http://cordova.apache.org/docs/en/edge/guide_cli_index.md.html#The%20Command-Line%20Interface

**Comment by xseignard** [comment]
And please tell me what is the serial device you use.

**Comment by harshali893** [comment]
The device I am using is hemoglobin Testing system.
And the chip is CP210

**Comment by harshali893** [comment]
I was mixing up phonegap and cordova. I just realised there are some differences.

**Comment by xseignard** [comment]
Hi @harshali893 any updates?
