### ISSUE TITLE
Error on install (cross-device link not permitted)

### ISSUE THREAD

**Issue by italomaia** [xseignard/cordovarduino#34]
Here is my output, folks:

    >> cordova plugin add https://github.com/xseignard/cordovarduino.git
    Fetching plugin "https://github.com/xseignard/cordovarduino.git" via git clone
    Repository "https://github.com/xseignard/cordovarduino.git" checked out to git ref "master".
    shell.js: internal error
    Error: EXDEV, cross-device link not permitted '/tmp/git/1439046983875/LICENSE'

**Comment by italomaia** [comment]
I had to clone the repository, then install it from the folder to make it work.

**Comment by xseignard** [comment]
It seems related to some folder permissions on your machine rather than a problem on the plugin itself, no?

Regards
