### ISSUE TITLE
How I get a element of the data arraybuffer

### ISSUE THREAD

**Issue by josb86** [xseignard/cordovarduino#36]
I ned get the elements of the data arraybuffer of the a serial.registerReadCallback 

serial.writeHex('BA0201B9',
                    function(successMessage) {
			document.getElementById("textinput2").value = "";
                        serial.registerReadCallback(
			function success(data){
				document.getElementById("textinput2").value += arrTOdecx(data);
				},
			function error(){
				document.getElementById("textinput2").value = "Failed to register read callback";
				});
                    },
                    errorCallback
                );

the function  arrTOdecx(buf) { //ArrayBuffer to dec
		var dat = new DataView(buf);
		alert(dat.byteLength);
		return parseInt(dat[2]); 
	}

the dat.byteLength say that length is 5. but parseInt(dat[2])  show NaN.

**Comment by xseignard** [comment]
Hi @josb86 any updates?

**Comment by xseignard** [comment]
Hello @josb86 
See https://github.com/xseignard/cordovarduino/issues/38#issuecomment-152814528 for a complete example

Closing the issue, feel free to reopen it if needed.
