### ISSUE TITLE
Need help with parsers

### ISSUE THREAD

**Issue by fuatsengul** [xseignard/cordovarduino#39]
Hi Xavier,
I know this project is standing still for one year, probably you've left development of it.
But I need some functionality like so: https://www.npmjs.com/package/serialport#parsers

I'm getting large data(memory dump) from connected device at once, almost 75Kb.
The device sending all the data together, and registerReadCallback getting all the data in a single event.
As the result, it crashes. I'm working with this device at two different platform, and as a node.js application, I can work with serialport package as I referenced above. Maybe there's a easy way to implement some parser like it, could you give me any insights about that? Is it applicable? Or is there any way for replacement?

**Comment by xseignard** [comment]
Hello,
Implement parsers on top of cordovaduino should be easy, see the source of the parsers here: https://github.com/voodootikigod/node-serialport/blob/master/parsers.js

Regarding the 75kb data, it may be another problem, could you please send a crash log?

Regards,

Xavier

**Comment by fuatsengul** [comment]
Hello Xavier, 
You're right, it's easy to implement this code after when data is received.
But with this data, registerReadCallback is not launched at all, so a top layer of parser wouldn't be helpful.
I need an event to get the data between every line feeds.
By the way, there's not any way to get crash log(if there's any) that I found. The only thing I see is when data is big enough, read callback is not emitted.

**Comment by xseignard** [comment]
Hi @fuatsengul sorry for late reply, I'm very busy.
Any updates?

**Comment by fuatsengul** [comment]
Hello Xavier, 
I found a way to messagging the device line-by-line, so the problem remains but I don't hit it anymore.
Probably someone will thought :)

**Comment by xseignard** [comment]
Hello @fuatsengul 
Please check my comment here : https://github.com/xseignard/cordovarduino/issues/38#issuecomment-152814528

Everything seems to work fine, but if you could adapt this code to your own use case and see how it behave with large amount of data it may be a nice way to solve your problem.

Regards

Xavier

**Comment by fuatsengul** [comment]
The problem is not about a corrupted data, it's about core of serial port.
If the data is bigger than its buffer (I suppose there is one) callback is not firing at all.

I'm getting almost 150KB of data at once, it takes about 20 seconds. I wait for maybe 5 minutes but saw nothing :( 

```
    serial.requestPermission(
        // if user grants permission
        function(successMessage) {
            // open serial port
            serial.open(
                {baudRate: 9600},
                // if port is succesfuly opened
                function(successMessage) {
                    open = true;
                    // register the read callback
                    serial.registerReadCallback(
                        function success(data){
                            // decode the received mess

                            //This never fired 
                        }
                    );
                }
            );
        }
    );

```

**Comment by DenverCoder-9** [comment]
I am also trying to move a project from node serial port ---- so my Parser is already written and works great, but I'm struggling with how I would implement a Parser using this plugin. 

@fuatsengul did you find success creating a parser?

**Comment by fuatsengul** [comment]
@DenverCoder-9 nop, sorry :/
I've tried a lot, but in my case, the data was so big (around 100KB) and device was sending it at once. So the library wouldn't handle it I suppose. I wasn't getting any callback. So I find a way to split the data from device itself, it lowered speed (around 90% slow now) but at least it works. The node library works great and never drops any data. But the problem probably comes from android itself. (my opinion)

**Comment by xseignard** [comment]
@DenverCoder-9 the issue @fuatsengul have might not be the same as yours, for a parser implementation, please check https://github.com/xseignard/cordovarduino/issues/38#issuecomment-152814528
