### ISSUE TITLE
"Error writing 2 bytes at offset 0 length=2" Need help

### ISSUE THREAD

**Issue by fuatsengul** [xseignard/cordovarduino#42]
Hi Xavier, 
I'm having another problem, this is the log message that I created with console logs at write and read sections:
```
writing: -REQ:CSTA:RB
readed:-REBOOT
readed:>Start
Error: Error writing 2 bytes at offset 0 length=2
```

The curious side of this problem is: it's working sometimes, and sometimes not.
I couldn't found any exact condition that triggers this issue.

Also check this out: https://github.com/mik3y/usb-serial-for-android/issues/91
Somebody had a very similar issue and solved their own way. 

Have it ring any bell for you?

**Comment by xseignard** [comment]
Hi @fuatsengul 
Without prior knowledge of your setup I cannot tell you much.
But it seems you are rebooting your device from android, maybe it is not fully rebooted?

Could you tell me more about your setup?

Regards

**Comment by xseignard** [comment]
With no more info I'm closing the issue.
Feel free to reopen it.

Regards

**Comment by MinhQuoc** [comment]
I have same issue here. When looping write data via cordova usb serial on ionic. In this case, I retry send the next error is 'Writing a closed port', therefore I should reopen port to continue to send.
