### ISSUE TITLE
Parser Implementation

### ISSUE THREAD

**Issue by cseemo** [xseignard/cordovarduino#45]
Similar to Issue #39, if anyone can help advise me how to use a parser with this plugin that would be awesome!!

I have a functional Electron (Atom) Desktop Application using Node Serial Port, with a parser that was written by a friend. I am hopeful to re-use this parser on an Android project that I'm building using Phonegap and Ionic. 

I have the plugin working, I am reading data from my USB device, but I need to parse it so that I can get my line by line data correctly formatted. 

Thanks for your help!

**Comment by xseignard** [comment]
That would be a great addition to this plugin!
Actually I'm thinking of migrating the API of this plugin to a `serialport` compatible API for quite a long time, but I never had time.

In the meantime, you could do something like this https://github.com/voodootikigod/node-serialport/blob/master/parsers.js#L11-L28 in the function you passed in the `registerReadCallBack`.

**Comment by xseignard** [comment]
Also see my comment here, for a line by line parser:
https://github.com/xseignard/cordovarduino/issues/38#issuecomment-152814528

**Comment by cseemo** [comment]
Thank you, Xavier. I definitely appreciate the point in the right direction. 

I want you to know your plugin rocks and I appreciate all of your help. If I might ask you another question, my hardware documentation says it sends out HEX values and the way I receive them in my Node Serial Port project is in Hex. I take the buffer and iterate through to create my hex sring:

    var msg = '';
    for(var i=0; i < data.length; i++){
        msg+= ' 0x'+data.toString('hex', i, i+1);
    }

    //msg=' 0x5a 0x4d 0x00 0x2e...

How would I get the data variable in the registerReadCallback() method into hex values? I have tried every method I can find online and cannot seem to get it to function. When I take the data variable and create a new Uint8Array() I get the proper dec values but my back-end is designed to parse the hex values so I'd prefer to keep it the same. 

Thanks again for all of your help!!

**Comment by xseignard** [comment]
Why not something like this ?
```
var decToHex = function(dec) { return '0x' + (+dec).toString(16); }
decToHex('28');
// returns '0x1c'
```

**Comment by xseignard** [comment]
Any updates?

**Comment by cseemo** [comment]
This plugin rocks!! All is well in my world it turned out my ignorance was in the way. Thank you for all of your efforts.
