### ISSUE TITLE
Write and read

### ISSUE THREAD

**Issue by yoave23** [xseignard/cordovarduino#47]
What would be the best approach for sending data to a device and wait for a response?
I tried to: Request permission => open port => write => read but got nothing
also tried:  Request permission => open port => register callback => write but also got nothing
The request permission => open port => write works well.
any suggestions?

**Comment by xseignard** [comment]
Hello,
Please provide more information:
- android version and device
- what kind of device you plug to android
- your code both android and device one (if there is any)

Also, please check the following code is ok for you:
https://github.com/xseignard/demoCordovarduino

Regards

Xavier
