### ISSUE TITLE
CDC device not working (v-usb based)

### ISSUE THREAD

**Issue by eni23** [xseignard/cordovarduino#48]
Hello

First of all thanks for that awsome library, this is awsome and works just perfect with FTDI or CP devices.

I have an attiny85-based device (Digispark), which comes with an handy CDC-library for Arduino. The cdc-library is using v-usb for communication, unfortunately with an custom vid (16d0) and pid (087e) whitout the option for changing it. 
I tried to specify nearly every possible combination of parameters, but cordovarduino seems unable to see that device. The device works fine under linux or even under android with an app called "USB Serial Term" and some chinese example app which is based on the cdc-mode of this driver: https://github.com/ksksue/FTDriver
Do you have any ideas what else i could try? Unfortunately i have basically no knowledge in java..

**Comment by xseignard** [comment]
Hello,

Thanks for your kind comment.

Have you tried the following?
```js
serial.requestPermission({
        vid: '16d0',
        pid: '087e',
        driver: 'CdcAcmSerialDriver'
    },
    function success(),
    function error()
);
```

It will tell cordovarduino to use `CdcAcmSerialDriver` for your device with the given vid/pid.

Let me know if it works.

Regards

**Comment by eni23** [comment]
Thanks for your answer!

Yes, i tried to specify the `CdcAcmSerialDriver` (and every other), tried vid and pid as integers, whitout pid/vid, different baudrates, nearly every combination possible. There is not even an "request permission" dialog, cordovarduino allways calls error-callback with the following message: `"No device found!"`

**Comment by xseignard** [comment]
It seems the CDC driver I use is not reliable for your microcontroller.

Have you tried https://github.com/digistump/DigiCDCPhonegap ?

**Comment by xseignard** [comment]
I think it would be pretty easy to add DigiCDC driver regarding the previous link.

**Comment by eni23** [comment]
Yes, i tried https://github.com/digistump/DigiCDCPhonegap
This 'library' seems really unfinished, config.xml specifies a source files which do not exist, and the reading function seems never tested and does not working at all, the function just looks copy pasted from the write function..
I would love to contribute this feauture, but unfortunately my java-skills are too low for understanding the code of  cordovarduino completeley..

**Comment by xseignard** [comment]
Ok, I could implement it, but with no real hardware it's always hard to achieve.

I'll try to find time to give a look.

**Comment by eni23** [comment]
This would make me very, very, very happy..
If it helps, i could send you such an device via mail, as i see you are living in france, so a mail from switzerland should arrive pretty fast..

**Comment by xseignard** [comment]
Hello, I never had time to do it.

Any updates on your side?

**Comment by alberiolima** [comment]
It works on clones
