### ISSUE TITLE
device not found after android reboot

### ISSUE THREAD

**Issue by lennozgs** [xseignard/cordovarduino#49]
Hello, 

Thanks for your work,

I use an arduino uno, 

I have an issue when i reboot my android tablet with the arduino plugged, 
When i launch my app without unplug the arduino, i have an error "No device found" and the led tx/rx in the arduino not blink.

If i unplug and plug the arduino i have no more problem.

Could you help me please ? :)

**Comment by xseignard** [comment]
Hello @lennozgs, sorry for the delay, i was really busy.

I guess the problem is that Android do not check if usb OTG is plugged at boot time so no event is fired and then your device is not found?

Did you find some usefull info? Sorry I cannot help more.
