### ISSUE TITLE
Question: Disconnect Detection?

### ISSUE THREAD

**Issue by PaulBeaudet** [xseignard/cordovarduino#51]
Is there possibly a way to detect when USB / Serial is disconnected? 
(in order to prompt re connection and stop running the application that depends on the Arduino)

I mean possible in the general sense as well as if its in the plugin somewhere, I wouldn't mind figuring out to add the feature if it doesn't exist and that is something that is desired

**Comment by xseignard** [comment]
re @PaulBeaudet 

please check #8. I don't have any other ideas than pinging arduino/serial.

**Comment by PaulBeaudet** [comment]
Xavier,

That's a good Idea! I should have thought of that. Thank You! 

As an aside, I really like the idea of the redundant data write attempt also.
I have already seen instances of dropped byte whilst accidentally running my robot into things, and it will just continuously do its last command because it dropped the "stop" serial message it's normally supposed to send. Actually it drops the serial connection entirely on wiggling the OTG connector, I have to close and open the serial connection to stop the bot. However, I could actually solve that issue by doing something similar to your example, basically reconnecting on a write error and holding the last message in closure, still pushing it through on the reconnection. Only possible with -> [this solution](https://github.com/xseignard/cordovarduino/issues/52). It would disconnect and reconnect from jostling the OTG connector and I wouldn't even know it! 

With that in mind the redundant write attempt, may be completely fruitless because once a write fails you will have to reconnect because the port needs permissions to reconnect even it was a millisecond disconnect event that caused the write failure. Maybe that's only my experience and there are other write failure conditions
