### ISSUE TITLE
Question: Asking for USB Permissions

### ISSUE THREAD

**Issue by PaulBeaudet** [xseignard/cordovarduino#52]
Is asking for USB permissions actually required? or can we possibly add permissions in the Android manifest, or something to that effect?

I mean I'm all for being polite and all, but my application is for a robot not a human

Much less compelled to be polite to robots.. Their potential uprising is greatly overblown

**Comment by xseignard** [comment]
Hello @PaulBeaudet please check my comment here : https://github.com/xseignard/cordovarduino/issues/31#issuecomment-93310108

You may find this useful if you use npm to build your app: https://github.com/mhartington/cordova-config-utils

Updating the docs is much welcome ;)

**Comment by PaulBeaudet** [comment]
Xavier,

Awesome, I should have backlogged more through the issues. Your previous comment referenced last post gets the job done. Now I just need to put a timeout on request permissions to auto connect it when I plug in. Thank You!

The versioning and build element of this type of project is still something I'm trying to get my head around, and solution like this might make either difficult but honestly I'm just happy that it is this simple for right now. 

----
I will add a couple things for other people looking at this.

Still call the request permissions method, I didn't try ONLY using serial.open but it seems like one of the other users did and I don't think the plugin is designed that way at the moment 

Also there is some presumption that all Arduinos of like models have like VIDs and PIDs. Not so, on a Unix system you will have to open up your command prompt and see what yours is for yourself. (im sure there is a similar way to find out on windows, I just don't know what it is)

`lsusb`
 
Then may be there will be a line like ( given an Arduino is plugged in )
`Bus 006 Device 007: ID 2341:0043 Arduino SA Uno R3 (CDC ACM)`

After ID its VID then PID so '2341' and '0043' were the strings that I needed to put into the device_filters.xml I created in my project

Arduinos of the same Model are not all the same because they are produced by different manufacturers, which... if you have been following the Arduino story closely, there has been quite a bit of drama around manufacturers

**Comment by xseignard** [comment]
> Still call the request permissions method, I didn't try ONLY using serial.open but it seems like one of the other users did and I don't think the plugin is designed that way at the moment

Yes I think we still need to call request permission, maybe I'll update the API to avoid such call in such situation.

> Arduinos of the same Model are not all the same because they are produced by different manufacturers, which... if you have been following the Arduino story closely, there has been quite a bit of drama around manufacturers

That's true, but in most case, if the serial over usb is the same as the official arduino, you should be good to go without specifying VID/PID.

Thanks for your feedback.

**Comment by PaulBeaudet** [comment]
`That's true, but in most case, if the serial over usb is the same as the official arduino, you should be good to go without specifying VID/PID.`

example Uno R3 vid/pin was - 9025:0067
Tested a few of the "Arduino's" I have handy
4 Uno R3s    - 2341:0043 ~Arduino SA
Yun               - 2341:8041 ~Arduino SA
2 Micros        - 2341:8037 ~Arduino SA
Teensy 3       - 16c0:0486
Usb Lillypad  - 1b4f:9208

The only thing in common is the VID for "Official" Arduino's ( in quotes to note official is a loose term now and days not to mock)

It definitely looks like PID changes model to model. Wouldn't be surprised if the VID changes country to country base on where the Arduino was manufactured

I would hesitate to say most cases the models information will be the same because our model information was definitely different and people are surely using different versions of Arduino besides the Uno even if it was true that the Uno mostly had the same VID/PIN

Maybe I should look for a listing to have an inclusive device_filter.xml

The other thing I notice now that I have looked at this more carefully is that it is effectively signalling the intent as opposed to requesting permission. I thought those two things where completely different, but it seems to effectively do two things in one go? Don't get me wrong, It's a pleasant surprise because that is exactly what I want. When I plug in the device, it runs the application as well as gives permission on request without prompt. Its great!

**Comment by xseignard** [comment]
I'm cleaning up issues here, and coming back to yours:

- VID is the "Vendor ID" : Arduino SA have its own (2341), and most of arduino clones will have the same as the genuine one (most of the time)
- PID is the "Product ID" : so it makes perfect sense to have one per model, and, here too, clones will have the same as the genuine model (most of the time)

I think I can close this issue.

@PaulBeaudet what about a pull request to update the readme about avoiding permission?

Regards
