### ISSUE TITLE
Reset Failed result = -1

### ISSUE THREAD

**Issue by DenverCoder-9** [xseignard/cordovarduino#54]
Hello,

First off I want to thank you for building this - it's been great. Recently I've been having some issues with my device recognizing the USB connection. I think my USB Host to Go cable might be going bad so I've ordered another one. 

In the meantime, I am getting a strange error when the USB is recognized - the error is Reset Failed result = -1. 

I scanned the source code files and cannot find the string "Reset Failed" anywhere. 

I believe this is being called after the Request Permission function - so it should be on the Serial Open command but I'm not entirely sure. 

Any idea where this error is being generated?

**Comment by justgeek** [comment]
Have same issue with Texas Instruments LauchPad

**Comment by xseignard** [comment]
Please be more specific!!

Code, devices and all the stuff

**Comment by lobodol** [comment]
Hi, I've got the same issue with my HTC One M9 and my Arduino Uno R3.
I first plugged my Arduino with OTG wire, then perform a "lsusb" with Terminal Emulator. I finaly put the VID & PID in the source code.
Should I open a new issue ?

Thanks.

**Comment by xseignard** [comment]
@lobodol yes, arduino should be seamlessly detected, even without VID and PID

**Comment by xseignard** [comment]
No updates, I close the issue.

Feel free to reopen it if needed.

**Comment by AmarKaygude** [comment]
Hi, 
I am trying to connect my ionic app to microchip through USB but getting Reset Failed result = -1 error when trying to serial open. requestPermission execute successfully but gives error for serial open function. Please check this issue.

requestPermission object
`{
vid: '04D8', 
pid: '003F',
driver: 'FtdiSerialDriver'
}`

object for serial open function
`{
    baudRate: 115200,
    dataBits: 8,
    stopBits: 1,
    parity: 1,
    dtr: true,
    rts: true,
    sleepOnPause: false
  }`
