### ISSUE TITLE
[solved] ReferenceError : serial is not defined

### ISSUE THREAD

**Issue by laRob95** [xseignard/cordovarduino#57]
Hey,

I tried to include cordovarduino plugin into my cordova project.

I tried a simple thing, but i have an error : ReferenceError : serial is not defined.

When i move the serial.js script in my js/ folder and include it in my html document, i have an other error : 
Uncaught ReferenceError: module is not defined                                    serial.js:72
Uncaught TypeError: Object #<Object> has no method 'exec'            serial.js:8

I don't know what i can do.

I use cordova 6.2.0
npm 1.4.21
android 4.4.2

I read this, but it not work for me
https://github.com/xseignard/cordovarduino/issues/26

**Comment by xseignard** [comment]
Hello,

Have you tried the complete example in the [README.md](https://github.com/xseignard/cordovarduino#a-complete-example) ?

Regards

**Comment by laRob95** [comment]
I solved it.

I have wrote this : 
	initialize : function() {
		document.addEventListener('deviceready', this.**onDeviceReady()**, false);
	},

instead of this : 
	initialize : function() {
		document.addEventListener('deviceready', this.onDeviceReady, false);
	},

and it works

but i don't know if i have to write anything in the config.xml in the root directory
like 
<plugin name="fr.drangies.cordova.serial" spec="0.0.7" />

because i saw this line after executed the command `cordova platforms add android`
<plugin name="cordova-plugin-whitelist" spec="1" />

**Comment by xseignard** [comment]
Just install cordovarduino as mentionned in the readme, and you should be ok, no need to touch file structure and xml

It seems you lack of understanding of cordova, please refer to the cordova documentation.
