### ISSUE TITLE
No device found ! or other problem of connection

### ISSUE THREAD

**Issue by laRob95** [xseignard/cordovarduino#58]
Hey,

I try to connect a some device to an android tablet.

I found 3 scenarios, i use specific vid and pid in each situation: 

- I connected a android phone to the tablet, the javascript can access to requestPermission, open and read function without error, but the content of the reading buffer is null, only zero.

- I connected an usb key and a Datalogic scanner to the tablet. The result is the same : can access to requestPermission, but the application close immediately after (crash). I don't know if open function is lunch.

- I connected a mouse or a keyboard to the tablet. I always have  a callback error of the requestPermission function, so i can't read information.

Here is the javascript code : 

	var console = function(message) {
		document.querySelector('.console').appendChild(document.createTextNode(message));
		document.querySelector('.console').appendChild(document.createElement('br'));
	};
	
	var errorCallback = function(message) {
		console(message);
	};
	
	var app = {
		
		initialize : function() {
			document.addEventListener('deviceready', this.onDeviceReady, false);
		},
		
		onDeviceReady : function() {
			console ('function onDeviceReady');
			document.querySelector('.start').addEventListener('click', app.start, false);
			document.querySelector('.stop').addEventListener('click', app.stop, false);
		},
		
		start : function(evt) {
			
			serial.requestPermission( {vid: '046d', pid:'c31c'},
				function(succesMessage) {
					console('requestPermission success');
					serial.open ( {baudeRate : 9600},
						function (succesMessage) {
							console('open success');
							
							//serial.read(
								//function(buffer){
									//console('enter read function');
									//console(buffer);
									//var view = new Uint8Array(buffer);
									//console(view);
									//console(view.length);
									//for (var i=0,c=view.length;i<c;i++) {
										//console(String(view[i]));
									//}
								//},
								//errorCallback
							//);
							
							//serial.registerReadCallback(function(data){
									//console('enter registerReadCallback');
									//var view = new Uint8Array(data);
									//console(view);
									//console(view.length);
								//}, 
								//errorCallback
							//);
						},
						//error open
						errorCallback
					);
				// error requestPermission
				},
				function(message) {
					console('permissionRequest Error : ' + message);
				}
			);
		},
		
		stop : function (evt) {
			serial.requestPermission( {vid: '046d', pid:'c31c'},
				function (successMessage) {
					serial.close(function(successMessage){
							console('close success');
						}, 
						errorCallback
					);
				},
				errorCallback
			);
		}
	};
	
	app.initialize();
		
	

My aim is to connect a scale on a tablet, but at this time i don't have it ...
So I try some code with things that I have.

I thought that if i can read a keyboard, i can read a scale, maybe the behavior is the same. 

But when I tried to connect a keyboard, i always have a message : 'No device found!'

**Comment by xseignard** [comment]
This is a plugin for **Serial** over USB devices, the devices you're mentionning don't seem to be ones!!

Please tell me what kind of device you're trying to plug to your phone, and be specific

**Comment by laRob95** [comment]
This is the device that I want to connect : http://www.precisa.ch/en/pr/gm/160BJ/
I have a RS232/usb adapter, and usb/micro-usb adapter.

I didn't have the right link (a RJ45/DB9 specific to the scale), but now i have it.

When I lunch the app and click 'start', I am asking for request permission, but the open function crash the app.

lsusb for vid and pid send me : 
Bus 002 Device 015: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port
and it is the vid/pid of the link I think. 

I have an other vif/pid, obtain when i tried to use android studio and the USB host API (but it's hard for me). But when i use them, I have the instruction : no device found.

I let default values for scale configuration, except this : IntErF to 8-n-1 (p30,p42 of the manual) for configure parity to 0 and 8 data bits.

Tell me if I'm wrong please.

**Comment by xseignard** [comment]
Could you please show me your code?

**Comment by laRob95** [comment]
I didn't change the code since my first post. I can add html file, there is no css

<!DOCTYPE html>
	<html>
	    <head>
			<meta charset="utf-8">
	        <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *">
	        <meta name="msapplication-tap-highlight" content="no">
	        <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">
	        <link rel="stylesheet" type="text/css" href="css/index.css">
	        <title>teSt3</title>
	    </head>
	    <body>
	        <div class="app">
				<button class="start">Start</button>
				<button class="stop">Stop</button>
				
				<div class="console">
					<h1>CONSOLE</h1>
				</div>
	        </div>
	        <script type="text/javascript" src="cordova.js"></script>
	        <script type="text/javascript" src="js/index.js"></script>
	
	
	    </body>
	</html>

I simply use serial.requestPermission and serial.open with a console message, and the app crash.

**Comment by xseignard** [comment]
Hello,
It seems the serial connection with PL2303 should work, see https://github.com/xseignard/cordovarduino/issues/14

Maybe @ndvalkov could tell us more?

In the meantime, could you try the following?

```
serial.requestPermission({
        vid: '067b',
        pid:'2303',
        driver: 'ProlificSerialDriver'
    },
    // the rest of your code here as usual
);
```

Regards

**Comment by laRob95** [comment]
It works, thank you !

Could you help me again ?

I'm not able to write to the serial port. I wrote

**Comment by laRob95** [comment]
It works, thank you !

Could you help me again ?

I am not able to use serial.write. I have this :

	serial.write(
		'DTEST123\r\n',
	
		function success() {
			console('write success');
		},
		errorCallback
	);
	
After this 

	serial.open ( {baudeRate : 9600, dataBits: 7, parity: 1}, ... );
	
according to the manual. May I need to fix parity on even ? How do this ?

I wrote on the serial port since the PC, with this : http://laboiteaphysique.fr/site/la-boite-outils/logiciels/term
and it works (the scale display test123).

But when I do the instruction with serial.write, nothing happen.

**Comment by xseignard** [comment]
So I checked the manual of your scale.
The serial port is a 7-E-1 this means:
- 7 data bits
- even parity
- 1 stop bits

With `serial.open ( {baudeRate : 9600, dataBits: 7, parity: 1}, ... );` you configured the serial port with:
- 7 data bits
- **odd** parity
- 1 stop bits

Could you try:
```
serial.open ( {baudeRate : 9600, dataBits: 7, parity: 2}, ... );
```

Btw, since `baudRate` defaults to `9600` there is no need to pass it, so you could write:
```
serial.open ( {dataBits: 7, parity: 2}, ... );
```

And it is the same with the `serial.requestPermission` the values I gave you are the default ones, so I don't understand why it works with:
```
serial.requestPermission({
        vid: '067b',
        pid:'2303',
        driver: 'ProlificSerialDriver'
    },
    // the rest of your code here as usual
);
```

but not with

```
serial.requestPermission(
    function success(),
    function error()
);
```

Regards

**Comment by laRob95** [comment]
It works with the default values (8 dataBits and parity to 0, and scale on 8-n-1).

So thank you, I have the weight on my android.

**Comment by xseignard** [comment]
@laRob95 well that's good news for you!

Would you mind to give a try to setup your scale with 7-E-1 and try cordovarduino with :
```
serial.open ( {dataBits: 7, parity: 2}, ... );
```

I never had the chance to test a device that is not 8-N-1, and your experiment would give precious feedback.

Regards!

btw: I think the `serial.open` part in the readme lacks of infromation about configuration options. I would be nice to provide a PR to improve it if you're up to!

Have fun!

**Comment by laRob95** [comment]
In 7-o-1 mode, I tried : 

    serial.open ( {dataBits: 7, parity: 1}, ... );

and it works.

in 7-E-1 mode, I tried : 

     serial.open ( {dataBits: 7, parity: 2}, ... );

but it doesn't work, the app crash.
I tried : 

    serial.open ( {dataBits: 7, parity: 1}, ... );

and I obtained a the log 'open success' but I can't obtain the weight. Nothing happen.

**Comment by xseignard** [comment]
Thanks! That's good to know.
So it seems the `even` parity does not work as expected.
I'll try to dig into this.

Regards!
