### ISSUE TITLE
question. cordovarduino on windows phone 8

### ISSUE THREAD

**Issue by paredesivan** [xseignard/cordovarduino#60]
There are possibilities of using the plugin in Windows Phone 8 ?

**Comment by xseignard** [comment]
Nope, AFAIK Windows Phone 8 don't even have any kind of Serial API, so it won't be possible at all, with this plugin or not.

If you have docs proving me wrong, please let me know so we can start to investigate

**Comment by d0mokun** [comment]
Does the same apply to the Windows universal platform?
