### ISSUE TITLE
No serial device on Android

### ISSUE THREAD

**Issue by dzean** [xseignard/cordovarduino#61]
Hi !
I am trying to test my Cordova project...
When I am using Arduino IDE to send an order when connecting the arduino uno to my computer, it's ok (baudrate 9600)

But when I do the same thing through my cordova project, I have "error : no device found" when trying serial.requestpermission :(

I installed the application "SerialMonitor" on my android phone, and when I try to connect (baudrate 9600), I also have "No serial device".

Here is the source code : 
`$("#connect_button").click(function(){
        serial.requestPermission(
            function success(){
                serial.open({baudRate: 9600}, 
                    function success(){
                        alert('Success OPEN');
                    }, function error(evt){
                        alert('Error OPEN');
                    }
                );
            }, 
            function error(evt){
                alert("Error: " + evt);
            }
        );
    });`

I am using an OTG cable like this : http://www.ldlc.com/fiche/PB00150664.html

I forgot something ? :/

Thanks for your help
Jean

**Comment by xseignard** [comment]
Please try the example given in the readme and tell me if it work.

**Comment by dzean** [comment]
Thanks for your answer.

I tried your example, but I have the same "Error: No device found!"

One question : since the arduino is working when I connect it to my computer, does it certify that the cable (not the OTG) I use is OK ?
Concerning the OTG cable, since the arduino is ON when I connect it to my phone (samsung S6), it should be also OK...

Maybe I have to configure something on my phone ?
For example in developper options there is an option "Configuration USB" : Charge, MTP, PTP, RNDIS, Audio source, Midi

I don't understand what I missed :(

Jean

**Comment by xseignard** [comment]
The arduino being ON doesn't assure you that your usb cable is ok
Is your arduino an offical one, or a clone?

What's the result of a lsusb?

**Comment by dzean** [comment]
Thanks for your answer.
Yes it is an official arduino uno (starter kit)

for the lsusb : I am on windows :)
But as I can communicate with the raduino from my computer, upload sketch and test serial communication...

It would be necessary to know if OTG cable is ok but I don't know how

**Comment by dzean** [comment]
I did a new test:
   - I downloaded ArduinoDroid on my Android phone
   - I plugged the arduino with the OTG and usb cable
   - I send the blink sketch and I was prompted for permission

So I have to search why it is not prompting when I run a cordova app !

**Comment by xseignard** [comment]
Are you confident with cordova??

The code you provided don't look like cordova bootstrap code?

**Comment by xseignard** [comment]
As stated in the Readme, you may need to add the `dtr: true` option to the open function.

Please try the following:

```
serial.open({ dtr: true }, ...);
```

No need to specify the baudrate since the value you provide is the default one.

Regards
