### ISSUE TITLE
Expected at least 2 bytes 

### ISSUE THREAD

**Issue by Citygun** [xseignard/cordovarduino#62]
Hello,

I'm currently working on a project where I have to read the value of a sensor. I'm using a FTDI devices.
I achieve to get the permission and get the access to the port. But when I want to read the data. I get the following error : "Expected at least 2 bytes" . 

Here is the source code of how I call the read function
`serial.read(`
             `function success(data){`
              `console.log(data);`
                 `alert("success read"+data);`

```
       `     },
            function error(evt)
            {
              console.log("erreur read");
              console.log(evt);
            }
          );
```

 `
In fact I just don't understand the error, and it's blocking me.

Thanks for your help.

**Comment by xseignard** [comment]
Hello,

Could you be more specific? What is your phone, device and full code?

Regards

**Comment by Citygun** [comment]
Hi,

Thanks for your answer.

I'm working with a tablet LG V500, And the device is a ftd2xx device,

Here is the function I call when I need to do the connexion to a Serial Device:

```javascript
fundUSBDevices()
{
//Ask for the permission
serial.requestPermission(
      function success(){
          alert("success permission");
          //Open the port
          serial.open(
              {baudRate:9600},
              function success(){
                  alert("success open");
                  //Read the data
                  serial.read(
                      function success(data){
                          console.log(data);
                          alert("success read"+data);
                      },
                      function error(evt)
                      {
                          console.log("error read");
                          console.log(evt);
                      }
                );
            },
            function error(evt)
            {
                console.log("error open");
            }
        );
    },
    function error(evt)
    {
        console.log("error permission");
        console.log(evt);
    }
  );
}
```

For the moment I just want to read what the device is sending to me. But when I try with the registerReadCallback function the data object doesn't have the value and when I try with the read function I have the "Expected at least 2 bytes" error. 

Regards

**Comment by Citygun** [comment]
Hello,

A little update, I manage to get this object in return of the read function :
![image](https://cloud.githubusercontent.com/assets/4558030/16642772/65d76008-4451-11e6-975b-8dbb72073a16.png)

But as you see, I don't have any data in it.

Here is the object I get when I use the registerReadCallback function, no data as well :
![image](https://cloud.githubusercontent.com/assets/4558030/16642914/be08e6d8-4452-11e6-9731-ee5f9b9ff4e3.png)

My FTDI device is sending a freeflow of data and I can read those data in bluetooth.

Regards

**Comment by xseignard** [comment]
Please show me your code...
