### ISSUE TITLE
How to use cordovarduino with ionic ? any help @ndvalkov @xseignard

### ISSUE THREAD

**Issue by soft00null** [xseignard/cordovarduino#63]

**Comment by soft00null** [comment]
@etx @xseignard @sdesalas @crapthings @elafargue @ndvalkov @nraboy any help to use cordova plugin as ng-cordova one.

**Comment by soft00null** [comment]
apologies for bothering folks, resolved!

**Comment by xseignard** [comment]
That's great that you solved it!

But for the next one asking the same, it would be great if you could document it a bit.

Regards,

Xavier

**Comment by soft00null** [comment]
sure i will post it ASAP.
