### ISSUE TITLE
How to support plugging-in Arduino while the app is running?

### ISSUE THREAD

**Issue by stefek99** [xseignard/cordovarduino#67]
Currently in the sample project we have `app.initialize` and if we don't have Arduino plugged in it throws an error.

I was thinking along these lines - http://stackoverflow.com/questions/15763159/detecting-when-a-usb-device-is-detached-on-android - `USB_XXX_DETACHED`

In that way I could plug-in Arduino while the app is running.

It's not mission critical (nice to have) so I'm asking if there are existing examples.

**Comment by xseignard** [comment]
Hello @stefek99 
AFAIK there's no sample doing it.

It would be a nice and pretty simple addition to this plugin.

**Comment by xseignard** [comment]
Closing it due to inactivity.
Feel free to reopen it.

**Comment by stefek99** [comment]
Yeah... I'm not an expert, back in a day I was simply restarting the app.
