### ISSUE TITLE
Error writing 1 bytes at offset 0 length=1

### ISSUE THREAD

**Issue by gurumelo** [xseignard/cordovarduino#72]
Hello, i am using olimexino with microcontroller 32U4 (arduino Leonardo clone)

At the beginning, all correct, i can use serial.write in the board, but in the third serial.write i obtain this error:

```
Error writing 1 bytes at offset 0 length=1
```

I tested with dtr: true, dtr and rts true, dtr false and rts true, but i hadn't good luck.

With the monitor serial in arduino IDE, all correct.

Any idea?

Thank you very much.

**Comment by xseignard** [comment]
Hello, are you sure baudrates match?

**Comment by xseignard** [comment]
Closing it since I don't have news.
