### ISSUE TITLE
can't connect

### ISSUE THREAD

**Issue by locsim** [xseignard/cordovarduino#74]
Hi,
I' trying to establish a serial connection between a pc and an android device.
I'm using a serial over usb cable, control pannel says it is CP210X.
The com port appears in the terminal on the pc side.

I tried various options in the serial.requestPermission call but all I can get is a "no device found" error message.
Any help appreciated!
Philippe

please see js code below:
`$(document).ready(function(){
    document.addEventListener("deviceready",onDeviceReady,false);      
});

function onDeviceReady(){
	alert('this is lcc running');
	serial.requestPermission({driver: 'Cp21xxSerialDriver' }, serial_permission_ok, serial_permission_fail);
	
function serial_permission_ok(){
	alert('sp_ok');
	}	
	
function serial_permission_fail(evt){
	alert('sp_fail');
	alert(evt);
	}	

}
`

**Comment by locsim** [comment]
Hi, nobody here?
Has anyone already tried to establish a serial communication between a PC and an android device?
Which type of cable did you use?

Thank you!

**Comment by xseignard** [comment]
Have you read the docs? Please check your vid/pid, and provide a more detailled situation.
I see only code that don't help me much...

**Comment by locsim** [comment]
Hi Xavier,
I found the reason some time after this post: on my phone (oneplus running android v5),  the usb host feature has to be enabled before it can be used.
Sorry I should have told before.
Cheers,
Philippe
