### ISSUE TITLE
How do you test using Android to PC?

### ISSUE THREAD

**Issue by cosmointeractive** [xseignard/cordovarduino#78]
I'm having a hard time figuring how to start using this. I have the plugin installed but can't see how to send data to a COM port. Have you done any development using a Windows environment?

**Comment by xseignard** [comment]
Nope I don't own a windows computer.
Did you figured it out? If so, please let us know.

**Comment by xseignard** [comment]
This plugin is meant for android devices.

Closing it due to inactivity.
Feel free to reopen it.
