### ISSUE TITLE
Getting the status of serial connection 

### ISSUE THREAD

**Issue by rammere** [xseignard/cordovarduino#8]
Hi,
Is there a way that I can get the status of the connection ? like getStatus function ? 
so it return connected , closed ..etc .
thnx in advance :D

**Comment by sureshkumar-s89** [comment]
Hello @xseignard,

I have added a peace of code on forked [repository](https://github.com/sureshkumar-s89/cordovarduino), to get the status of usb device as an action to the plugin (serial.usbStatus). Here is the [link](https://github.com/xseignard/cordovarduino/compare/master...sureshkumar-s89:master) to comparison of code. But this will give only the status and only when we call this action.

Could you please take a review to check whether this will work? 

Also, Is it possible to create callback function for usbStatus as well? like you created a callback function for read process whenever we get new data (registerReadCallback). 

If yes, could you please show how to create callback for usbStatus?

**Comment by sureshkumar-s89** [comment]
I have removed the previous changes from [repository](https://github.com/sureshkumar-s89/cordovarduino). Now I have added only 
```
filter.addAction(UsbManager.ACTION_USB_DEVICE_ATTACHED);
filter.addAction(UsbManager.ACTION_USB_DEVICE_DETACHED);
```
 these two lines in Serial.java file (refer to [changes](https://github.com/xseignard/cordovarduino/compare/master...sureshkumar-s89:master)) to detect device disconnect status and exit application when disconnected.

To make it work, we need to add the following device attached and detached events in **AndroidManifest.xml** file under platforms/android directory:

```
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.hardware.usb.action.USB_DEVICE_ATTACHED" />
            </intent-filter>
            <meta-data android:name="android.hardware.usb.action.USB_DEVICE_ATTACHED" android:resource="@xml/device_filter" />
        </activity>
        <receiver android:name="MainActivity">
            <intent-filter>
                <action android:name="android.hardware.usb.action.USB_DEVICE_DETACHED" />
            </intent-filter>
            <meta-data android:name="android.hardware.usb.action.USB_DEVICE_DETACHED" android:resource="@xml/device_filter" />
        </receiver>
```
And also we need to add a new file **device_filter.xml** under platforms/android/res/xml with following contents:
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <usb-device vendor-id="067b" />
    <!-- Vendor ID of USB serial device -->
</resources>
```
Then build the cordova application, it will work. But when we remove and add android platform, above xml file changes will not be restored and we need to do it again.
