### ISSUE TITLE
No Device Found

### ISSUE THREAD

**Issue by tatsapp** [xseignard/cordovarduino#80]
Hi

    I am trying to connect Arduino Due device with my android device using cordovarduino plugin.
    But unfortunately I am getting "No device found" alert. 
    I am confused whether this plugin will work  for Arduino Due or is there a exception for this device?
    If there is no exception then kindly guide me to connect Arduino to android device.
  
   I am using the same code given in [https://github.com/xseignard/cordovarduino]

**Comment by xseignard** [comment]
What is the VID/PID of your arduino device?

**Comment by tatsapp** [comment]
2341:003e

**Comment by xseignard** [comment]
https://github.com/xseignard/cordovarduino#your-device-is-not-yet-known

**Comment by Prithivraj200** [comment]
No luck. It still displays  as no device found.

**Comment by tatsapp** [comment]
No luck. Still I am getting the same message(No device found).

**Comment by xseignard** [comment]
Do you still have issue with this?
If so, please show me some code.
If not, please share your solution.

**Comment by xseignard** [comment]
Closing it due to inactivity.
Feel free to reopen it.
