### ISSUE TITLE
HID Protocol

### ISSUE THREAD

**Issue by eruecco87** [xseignard/cordovarduino#81]
Can I connect to a HID USB device using this?
Is there any difference in connection between serial and HID?

I'm trying to connect to this http://www.wismec.com/product/predator-228/

**Comment by eribeiro9** [comment]
I am able to connect to my HID OMNIKEY 5427 CK by passing the VID/PID object. For me, I used `{ vid: '076B', pid: '5427' }`.  You will definitely have to find your PID in the documentation and maybe a different VID (I think the one I used is specific to OMNIKEY readers).

I am able to open the connection, but having trouble with `serial.registerReadCallback` at the moment.

**Comment by eruecco87** [comment]
Thanks for the answer, I do have a VID and PID for the device, it's supposed to be 0x0416/ 0x5020 though I'm not sure that's the right format.

**Comment by xseignard** [comment]
Did you still have troubles with that? If so tell me, if not, please detail what you have done for others.

**Comment by eruecco87** [comment]
@xseignard I couldn't figure it out so I abandoned the idea :(

**Comment by xseignard** [comment]
Ok, this plugin is not meant to do so, it would require more work to get HID working.

**Comment by aicos** [comment]
@xseignard, how long do you think it would take for someone to develop a new plugin that does this (if they had the experience) ?
