### ISSUE TITLE
Will this work on /dev/ttySAC1?

### ISSUE THREAD

**Issue by peterterbe** [xseignard/cordovarduino#82]
I'm trying to use a receipt printer that sits on /dev/ttySAC1. Can I use this plugin to communicate with this specific port? How can I select which port to open?
Thanks in advance!

requestPermission() says `No device found!`
From the dmesg the device has a prolific2303. Shall I tell it to use the prolific driver?
```
<6>[    1.354703] USB Serial support registered for pl2303
<6>[    1.354754] usbcore: registered new interface driver pl2303
<6>[    1.354787] pl2303: Prolific PL2303 USB to serial adaptor driver
<6>[    1.566413] DWC_OTG: ^^^^^^^^^^^^^^^^^Device Mode
<6>[    1.566454] usb20_otg usb20_otg: DWC OTG Controller
<6>[    1.566552] usb20_otg usb20_otg: new USB bus registered, assigned bus number 1
<6>[    1.566614] usb20_otg usb20_otg: irq 48, io mem 0x00000000
<6>[    1.566647] DWC_OTG: dwc_otg_hcd_start controller in device mode,everest
<6>[    1.566718] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
<6>[    1.566762] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
<6>[    1.566804] usb usb1: Product: DWC OTG Controller
<6>[    1.566831] usb usb1: Manufacturer: Linux 3.0.101+ dwc_otg_hcd
<6>[    1.566865] usb usb1: SerialNumber: usb20_otg
```

edit:
I have tried with ```{
      vid: '1d6b',
      pid: '0002',
      driver: 'ProlificSerialDriver'
    }``` and ```{
      driver: 'ProlificSerialDriver'
    }``` without any luck.

**Comment by azamalvi** [comment]
are you able to fix this issue?

**Comment by peterterbe** [comment]
> are you able to fix this issue?

No, I had to write a cordova plugin to handle the devices. This was surprisingly easy after reading the documentation though.

**Comment by azamalvi** [comment]
> > are you able to fix this issue?
> 
> No, I had to write a cordova plugin to handle the devices. This was surprisingly easy after reading the documentation though.

That's great. Can you please share your cordova plugin so that I can use it.

**Comment by peterterbe** [comment]
> > > are you able to fix this issue?
> > 
> > 
> > No, I had to write a cordova plugin to handle the devices. This was surprisingly easy after reading the documentation though.
> 
> That's great. Can you please share your cordova plugin so that I can use it.

Here you are. It's for a specific device using the Android SDK of that device. It had a receipt printer and a two lines LCD display. I used this plugin to handle both of them with only these high level methods so I doubt you can use this with an other device. It was an android based POS terminal from Wintec.

[client_plugin_src_cordova-plugin-wintec_src_android_WintecPlugin.zip](https://github.com/xseignard/cordovarduino/files/5474121/client_plugin_src_cordova-plugin-wintec_src_android_WintecPlugin.zip)

**Comment by azamalvi** [comment]
Thanks for this. But I am using Ionic for my application so it's looks like that this will not help me to fix my problem.
Or what else I can do to fix it for my ionic app using `cordovarduino` plugin

**Comment by peterterbe** [comment]
> Thanks for this. But I am using Ionic for my application so it's looks like that this will not help me to fix my problem.
> Or what else I can do to fix it for my ionic app using `cordovarduino` plugin

I was using Ionic, too. This was a long time ago but I suppose Ionic is still using Cordova under the hood so you can use your cordova plugin in Ionic.
