### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gitsad** [xseignard/cordovarduino#90]
Is it the MIT License ?

**Comment by xseignard** [comment]
Hello! yes it is!
I realized the LICENSE.md is missing, adding it asap.

Feel free to reopen this issue if needed.

Regards

**Comment by xseignard** [comment]
hum, maybe not very awake this morning, the license file is here: https://github.com/xseignard/cordovarduino/blob/master/LICENSE

is there anything wrong?

**Comment by gitsad** [comment]
Of course not, Thanks. Sorry for being blind. 😅

**Comment by xseignard** [comment]
we were both blind on this one ;)

happy hacking, let me know if anything goes wrong,

regards!
